[versions]
springBoot = "3.4.12"
springDependencyManagement = "1.1.7"
sonarqube = "7.5.0.8588"
jacoco = "0.8.11"

[libraries]
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
lombok = { module = "org.projectlombok:lombok" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }